import Std.Net.Addr

/-
The harness of lean-runtime's native micro-benchmarks (`benches/README.md`): what every
`Bench/<Name>.lean` shares with its Rust twin in `benches/rust/` (the LCG, the inputs, the
checksum), value for value with `benches/rust/src/lib.rs`, and the timed entry point. Written by
hand; the benchmark modules are generated by `scripts/gen_benches.py`.
-/

/-- The identity, so that generated code can write `e.toUInt64` whatever the width of `e`. -/
@[inline] def UInt64.toUInt64 (x : UInt64) : UInt64 := x

namespace Bench

/-- Opaque pass-through. Lean cannot see into it, so the value is forced here and nowhere else:
without it the pure input and kernel are sunk past both clock reads (leanrs's probe,
docs/07-benchmark-suite/3.1-program-contract.md S3). -/
@[noinline] def pin {α : Type} (x : α) : BaseIO α := pure x

/-- The LCG both sides draw their operands from: `x' = x * A + C` modulo 2^64. -/
@[inline] def step (x : UInt64) : UInt64 := x * 6364136223846793005 + 1442695040888963407

/-- The LCG's first state in the timed loop. -/
def SEED : UInt64 := 0x9E3779B97F4A7C15

/-- The LCG's first state when the inputs are built. -/
def INPUT_SEED : UInt64 := 0x2545F4914F6CDD1D

/-- The size of an operand or position array (the loop indexes it with the top 12 bits). -/
def ARRAY : Nat := 4096

/-- The checksum step: rotate and xor. -/
@[inline] def mix (acc r : UInt64) : UInt64 := ((acc <<< 7) ||| (acc >>> 57)) ^^^ r

/-! ## Inputs -/

/-- 64 copies of "a€😀é0123" (characters of 1 to 4 bytes, 896 bytes). -/
def mixed : String := String.join (List.replicate 64 "a€😀é0123")

/-- 896 bytes of ASCII. -/
def ascii : String := String.join (List.replicate 64 "abcdefgh012345")

/-- 16 strings that differ from `mixed` at different depths (variant k has a `b` for the `a`
that starts chunk 4k, for k < 15; the last is `mixed` itself). -/
def variants : Array String :=
  let base := mixed
  let vs := (List.range 15).map fun k =>
    let cut := 14 * 4 * k
    String.Pos.Raw.extract base ⟨0⟩ ⟨cut⟩ ++ "b" ++
      String.Pos.Raw.extract base ⟨cut + 1⟩ ⟨base.utf8ByteSize⟩
  (vs ++ [base]).toArray

/-- NaN, -NaN, inf, -inf, 0, -0, the largest finite value, the smallest subnormal. -/
def specials : Array Float :=
  #[Float.ofBits 0x7FF8000000000000, -(Float.ofBits 0x7FF8000000000000),
    Float.ofBits 0x7FF0000000000000, -(Float.ofBits 0x7FF0000000000000), Float.ofBits 0,
    -(Float.ofBits 0), Float.ofBits 0x7FEFFFFFFFFFFFFF, Float.ofBits 1]

/-- `ARRAY` operands uniform in `[lo, lo + width)` (given by their bits), every eighth one a
special value when `sp`. -/
def f64Operands (lo width : UInt64) (sp : Bool) : FloatArray := Id.run do
  let lo := Float.ofBits lo
  let width := Float.ofBits width
  let scale := Float.ofBits 0x3CA0000000000000
  let mut xs := FloatArray.emptyWithCapacity ARRAY
  let mut x := INPUT_SEED
  for k in [0:ARRAY] do
    x := step x
    if sp && k % 8 == 7 then
      xs := xs.push specials[(k / 8) % 8]!
    else
      xs := xs.push (lo + ((x >>> 11).toFloat * scale) * width)
  return xs

/-- Two operand arrays, for the binary functions (the second reversed). -/
def f64Pairs (lo width lo2 width2 : UInt64) : FloatArray × FloatArray :=
  let ys := f64Operands lo2 width2 false
  (f64Operands lo width false, ⟨ys.data.reverse⟩)

/-- A string and `ARRAY` positions in it. -/
structure PosInput where
  s : String
  ps : Array Nat

/-- Which positions: 0 any byte position up to two past the end, 1 a byte position before the
end, 2 a character start before the end, 3 a character start or the end. -/
def posInput (s : String) (kind : Nat) : PosInput := Id.run do
  let len := s.utf8ByteSize.toUInt64
  let starts := ((List.range (s.utf8ByteSize + 1)).filter fun i =>
    String.Pos.Raw.isValid s ⟨i⟩).toArray
  let mut ps := Array.emptyWithCapacity ARRAY
  let mut x := INPUT_SEED
  for _ in [0:ARRAY] do
    x := step x
    let p := match kind with
      | 0 => (x % (len + 2)).toNat
      | 1 => (x % len).toNat
      | 2 => starts[(x % (starts.size - 1).toUInt64).toNat]!
      | _ => starts[(x % starts.size.toUInt64).toNat]!
    ps := ps.push p
  return ⟨s, ps⟩

/-- A string and `ARRAY` valid positions of it, for `String.extract`. -/
structure ValidInput where
  s : String
  ps : Array s.Pos

def validInput (s : String) : ValidInput :=
  let raw := (posInput s 3).ps
  ⟨s, raw.filterMap fun p => s.pos? ⟨p⟩⟩

/-- The valid position at index `i` (the start out of range). -/
@[inline] def pick (s : String) (ps : Array s.Pos) (i : Nat) : s.Pos :=
  if h : i < ps.size then ps[i] else s.startPos

/-! ## Nat, Int, arrays, text (batch 2) -/

/-- `ARRAY` Nats below 2^24 (the LCG's top 24 bits). -/
def natOperands : Array Nat := Id.run do
  let mut xs := Array.emptyWithCapacity ARRAY
  let mut x := INPUT_SEED
  for _ in [0:ARRAY] do
    x := step x
    xs := xs.push (x >>> 40).toNat
  return xs

/-- `ARRAY` bytes (the LCG's top 8 bits). -/
def byteOperands : ByteArray := Id.run do
  let mut xs := ByteArray.emptyWithCapacity ARRAY
  let mut x := INPUT_SEED
  for _ in [0:ARRAY] do
    x := step x
    xs := xs.push (x >>> 56).toUInt8
  return xs

/-- The 64 bytes 0, 1, ..., 63. -/
def srcBytes : ByteArray := ⟨(List.range 64).toArray.map (·.toUInt8)⟩

/-- 16 characters, escapes among them. -/
def charOperands : Array Char :=
  #['a', 'z', '0', ' ', '\n', '\t', '\\', '"', '\'', '\x00', '\x1f', '\x7f', '\u0080', 'é', '€', '😀']

/-- 16 strings with escapes. -/
def quoteStrings : Array String :=
  (List.range 16).toArray.map fun k =>
    s!"item {k}: \"q\" \\ tab\there\n" ++ String.join (List.replicate k "é")

/-- 16 IPv4 texts, valid and not. -/
def ipv4Texts : Array String :=
  #["192.168.1.1", "10.0.0.255", "127.0.0.1", "255.255.255.255", "0.0.0.0", "8.8.8.8",
    "172.16.254.3", "100.64.0.1", "256.1.1.1", "1.2.3", "01.2.3.4", "1.2.3.4.5", "abc", "",
    "203.0.113.77", "198.51.100.24"]

/-- 16 IPv6 texts, valid and not. -/
def ipv6Texts : Array String :=
  #["::", "::1", "fe80::1", "2001:db8::1", "2001:db8:85a3::8a2e:370:7334",
    "::ffff:192.0.2.128", "1:2:3:4:5:6:7:8", "fe80::1%eth0",
    "2001:0db8:0000:0000:0000:ff00:0042:8329", "1::2::3", "12345::", ":::", "::ffff:1.2.3",
    "ABCD:EF01:2345:6789:ABCD:EF01:2345:6789", "64:ff9b::192.0.2.33", "ff02::fb"]

/-- 16 IPv4 addresses. -/
def ipv4Addrs : Array Std.Net.IPv4Addr :=
  #[.ofParts 192 168 1 1, .ofParts 10 0 0 255, .ofParts 127 0 0 1, .ofParts 255 255 255 255,
    .ofParts 0 0 0 0, .ofParts 8 8 8 8, .ofParts 172 16 254 3, .ofParts 100 64 0 1,
    .ofParts 1 2 3 4, .ofParts 203 0 113 77, .ofParts 198 51 100 24, .ofParts 224 0 0 251,
    .ofParts 169 254 10 20, .ofParts 9 99 199 255, .ofParts 1 0 0 1, .ofParts 100 100 100 100]

/-- 16 IPv6 addresses (zero runs of each length and place, IPv4 tails). -/
def ipv6Addrs : Array Std.Net.IPv6Addr :=
  #[.ofParts 0 0 0 0 0 0 0 0, .ofParts 0 0 0 0 0 0 0 1, .ofParts 0xfe80 0 0 0 0 0 0 1,
    .ofParts 0x2001 0xdb8 0 0 0 0 0 1, .ofParts 0x2001 0xdb8 0x85a3 0 0 0x8a2e 0x370 0x7334,
    .ofParts 0 0 0 0 0 0xffff 0xc000 0x280, .ofParts 1 2 3 4 5 6 7 8,
    .ofParts 0x2001 0xdb8 0 0 0 0xff00 0x42 0x8329,
    .ofParts 0xabcd 0xef01 0x2345 0x6789 0xabcd 0xef01 0x2345 0x6789,
    .ofParts 0x64 0xff9b 0 0 0 0 0xc000 0x221, .ofParts 0xff02 0 0 0 0 0 0 0xfb,
    .ofParts 0 0 0 0 0 0 0x102 0x304, .ofParts 1 0 0 2 0 0 0 3, .ofParts 1 0 2 0 3 0 4 0,
    .ofParts 0xffff 0xffff 0xffff 0xffff 0xffff 0xffff 0xffff 0xffff,
    .ofParts 0xfe80 0 0 0 0x202 0xb3ff 0xfe1e 0x8329]

/-! ## Running -/

/-- Runs one benchmark: N from the single argument, the input built and pinned before the first
clock read, the kernel's result pinned before the second; prints the result on line 1 and
`kernel_ns <ns>` on line 2. -/
def run {I : Type} (build : Unit → IO I) (kernel : I → UInt64 → UInt64)
    (args : List String) : IO UInt32 := do
  match args.map String.toNat? with
  | [some n] =>
    let input ← pin (← build ())
    let n ← pin n.toUInt64
    let t0 ← IO.monoNanosNow
    let out ← pin (kernel input n)
    let t1 ← IO.monoNanosNow
    IO.println (toString out)
    IO.println s!"kernel_ns {t1 - t0}"
    return 0
  | _ =>
    IO.eprintln "usage: <benchmark> N"
    return 2

end Bench
